name: CI-CD-Demo
run-name: ${{ github.actor }} to CI-CD-DEMO
on: [push]

jobs:
  build-ci-cd:
    name: Build-CI-CD
    runs-on: ubuntu-latest

    steps:

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: user/app:latest