name: CI-CD-Demo
run-name: ${{ github.actor }} to CI-CD-DEMO
on: [push]

jobs:
  build-ci-cd:
    name: Build-CI-CD
    runs-on: ubuntu-latest
      permissions:
        contents: read
        packages: write

    steps:

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
