name: Java CI
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

     - uses: mr-smithers-excellent/docker-build-push@v5
       name: Build & push Docker image
       with:
        image: sflorenz05/app-ci-cd
        context: ./
        tags: v1, latest
        registry: index.docker.io
        dockerfile: ./Dockerfile
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}